"""
Executive Summary Report Component.

Generate and export markdown reports.
"""

import streamlit as st
from datetime import datetime

from ui.utils.api_client import get_client


def render_report() -> None:
    """Render the executive summary report view."""
    st.header("📄 Executive Summary")
    st.caption("Generate partner-ready due diligence report")
    
    # Check for selected documents
    if not st.session_state.selected_document_ids:
        st.info("Select documents first. Go to Upload page.")
        if st.button("📁 Go to Upload"):
            st.session_state.current_page = "upload"
            st.rerun()
        return
    
    # Configuration
    st.subheader("⚙️ Report Options")
    
    col1, col2 = st.columns(2)
    
    with col1:
        include_timeline = st.checkbox("Include Timeline", value=True)
        include_missing_docs = st.checkbox("Include Missing Documents", value=True)
    
    with col2:
        include_graph_summary = st.checkbox("Include Entity Summary", value=True)
        formal_style = st.checkbox("Formal Memo Style", value=True)
    
    st.markdown("---")
    
    # Generate button
    if st.button("🚀 Generate Report", type="primary", use_container_width=True):
        _generate_report(include_timeline, include_missing_docs)
    
    # Show generated report
    if st.session_state.get("generated_report"):
        st.markdown("---")
        _render_generated_report()


def _generate_report(include_timeline: bool, include_missing_docs: bool) -> None:
    """Generate the executive summary report."""
    
    with st.spinner("Generating executive summary..."):
        try:
            client = get_client()
            
            result = client.generate_report(
                document_ids=st.session_state.selected_document_ids,
                include_timeline=include_timeline,
                include_missing_docs=include_missing_docs,
            )
            
            st.session_state.generated_report = result
            st.success("Report generated successfully!")
            st.rerun()
            
        except Exception as e:
            st.error(f"Failed to generate report: {e}")
            
            # Generate fallback report
            st.session_state.generated_report = _generate_fallback_report()
            st.warning("Generated fallback report (API unavailable)")


def _generate_fallback_report() -> dict:
    """Generate a fallback report when API is unavailable."""
    
    results = st.session_state.get("analysis_results", {})
    conflicts = st.session_state.get("conflicts", [])
    
    conflict_count = len(conflicts)
    critical_count = len([c for c in conflicts if c.get("severity") == "critical"])
    
    markdown = f"""
# Due Diligence Summary

**Generated:** {datetime.now().strftime("%B %d, %Y")}  
**Documents:** {len(st.session_state.selected_document_ids)}  
**Conflicts:** {conflict_count}

---

## Executive Overview

This analysis reviewed {len(st.session_state.selected_document_ids)} documents for the pending transaction.
{conflict_count} conflicts were identified, including {critical_count} critical issues requiring immediate attention.

---

## Critical Issues ⚠️

"""
    
    critical_conflicts = [c for c in conflicts if c.get("severity") == "critical"]
    
    if critical_conflicts:
        for i, conflict in enumerate(critical_conflicts[:5], 1):
            markdown += f"{i}. **{conflict.get('title', 'Conflict')}**: {conflict.get('description', 'N/A')[:100]}\n\n"
    else:
        markdown += "No critical issues identified.\n\n"
    
    markdown += """
---

## Recommendations

- [ ] Review all flagged conflicts with legal counsel
- [ ] Obtain any referenced documents not yet provided
- [ ] Confirm key figures (salary, equity) with counterparty
- [ ] Document resolution of each conflict

---

*This report was generated by the Cross-Document Conflict Detector.*
"""
    
    return {
        "status": "success",
        "summary_markdown": markdown,
        "conflict_count": conflict_count,
        "document_count": len(st.session_state.selected_document_ids),
        "has_critical_issues": critical_count > 0,
        "model_used": "fallback",
        "critical_issues": [c.get("title") for c in critical_conflicts],
        "key_findings": [],
        "action_items": [],
    }


def _render_generated_report() -> None:
    """Render the generated report with export options."""
    
    report = st.session_state.generated_report
    
    # Report header
    col_title, col_actions = st.columns([3, 1])
    
    with col_title:
        st.subheader("📋 Generated Report")
        st.caption(f"Model: {report.get('model_used', 'unknown')}")
    
    with col_actions:
        # Copy button
        if st.button("📋 Copy to Clipboard"):
            st.code(report.get("summary_markdown", ""), language=None)
            st.info("Select and copy the text above")
        
        # Download button
        markdown_content = report.get("summary_markdown", "")
        st.download_button(
            label="⬇️ Download",
            data=markdown_content,
            file_name=f"due_diligence_report_{datetime.now().strftime('%Y%m%d')}.md",
            mime="text/markdown",
        )
    
    st.markdown("---")
    
    # Quick stats
    col1, col2, col3 = st.columns(3)
    
    with col1:
        st.metric("Documents", report.get("document_count", 0))
    with col2:
        st.metric("Conflicts", report.get("conflict_count", 0))
    with col3:
        has_critical = "⚠️ Yes" if report.get("has_critical_issues") else "✅ No"
        st.metric("Critical Issues", has_critical)
    
    st.markdown("---")
    
    # Key findings
    if report.get("key_findings"):
        with st.expander("🔑 Key Findings", expanded=True):
            for finding in report["key_findings"]:
                st.markdown(f"- {finding}")
    
    # Critical issues
    if report.get("critical_issues"):
        with st.expander("⚠️ Critical Issues", expanded=True):
            for issue in report["critical_issues"]:
                st.error(issue)
    
    # Action items
    if report.get("action_items"):
        with st.expander("📝 Action Items", expanded=True):
            for item in report["action_items"]:
                st.checkbox(item, key=f"action_{item[:20]}")
    
    st.markdown("---")
    
    # Full markdown report
    st.subheader("📄 Full Report")
    
    with st.container():
        st.markdown(
            report.get("summary_markdown", "*No content available*"),
            unsafe_allow_html=False,
        )
